export const booksList = [
    {
        image: "./src/book-essencialismo.jpg",
        title: "Essencialismo",
        subtitle: "A disciplina busca por menos",
        author: "Greg McKeown",
        publisher:"Sextance",
        pages: "268",
        status: "read",//
        rating: "9.5",
        note: "",
    },
    {
        image: "./src/book-inventealgumacoisa.jpg",
        title: "Invente alguma coisa",
        subtitle: "",
        author: "Chuck Palahniuk",
        publisher:"Leya",
        pages: "335",
        status: "unread",//
        rating: "",
        note: "",
    },
    {
        image: "./src/book-ainvasao.jpg",
        title: "A invasão",
        subtitle: "Terra Gris II",
        author: "Peadar O'Guilin",
        publisher:"Melhoramentos",
        pages: "288",
        status: "reading",//
        rating: "",
        note: "",
    },
    {
        image: "./src/book-aconvocacao.jpg",
        title: "A convocação",
        subtitle: "Terra Gris I",
        author: "Peadar O'Guilin",
        publisher:"Melhoramentos",
        pages: "271",
        status: "read",//
        rating: "8.2",
        note: "",
    },
    {
        image: "./src/book-adivinacomediainferno.jpg",
        title: "A divina comédia",
        subtitle: "Inferno",
        author: "Dante Alighieri",
        publisher:"Novo Século",
        pages: "335",
        status: "unread",
        rating: "",
        note: "",
    },
    {
        image: "./src/book-memoriaspostumasdebrascubas.jpg",
        title: "Memórias póstumas de Brás Cubas",
        subtitle: "",
        author: "Machado de Assis",
        publisher:"Amoler",
        pages: "230",
        status: "unread",
        rating: "",
        note: "",
    },
    {
        image: "./src/book-coragemdeexistir.jpg",
        title: "Coragem de existir",
        subtitle: "Por uma vida digna de ser vivida.",
        author: "Matheus Jacob",
        publisher:"Buzz",
        pages: "103",
        status: "read",
        rating: "8.0",
        note: "",
    },
    {
        image: "./src/book-maisiedobbs2.jpg",
        title: "Maisie Dobbs",
        subtitle: "O caso das penas brancas",
        author: "Jackeline Winspear",
        publisher:"Arqueiro",
        pages: "317",
        status: "unread",
        rating: "",
        note: "",
    },
    {
        image: "./src/book-maisiedobbs.jpeg",
        title: "Maisie Dobbs",
        subtitle: "",
        author: "Jackeline Wisnpear",
        publisher:"Arqueiro",
        pages: "285",
        status: "read",
        rating: "8.0",
        note: "",
    },
    {
        image: "./src/book-nosufoco.jpg",
        title: "No sufoco",
        subtitle: "",
        author: "Chuck Palahniuk",
        publisher:"Leya",
        pages: "271",
        status: "read",
        rating: "7.5",
        note: "A trama de um protagonista egocêntrico, babaca e sexólatra. Essa obra aborda a vida com uma visão dura e necessária em tempos contemporâneos.",
    },
    {
        image: "./src/book-cavaleirodossetereinos.jpg",
        title: "O Cavaleiro dos sete reinos",
        subtitle: "",
        author: "George R.R. Martin",
        publisher:"Leya",
        pages: "413",
        status: "read",
        rating: "8.5",
        note: "Uma magnífica obra, ambientada no universo das Crônicas de Gelo e Fogo. A obra prende sua atenção em todo o tempo de leitura, abordando as lutas com uma narrativa impecável.",
    },
    {
        image: "./src/book-1984.jpg",
        title: "1984",
        subtitle: "",
        author: "George Orwell",
        publisher:"Leya",
        pages: "319",
        status: "read",
        rating: "9.2",
        note: "Sem dúvida alguma, uma obra que deve ler lida antes de morrer. Contribui para o desenvolvimento de pensamento crítico, além de levantar importantes questionamentos sobre nossa sociedade, levando em consideração a história distópica retratada na obra.",
    },
    {
        image: "./src/book-freud.webp",
        title: "Psicologia aplicada de Freud",
        subtitle: "",
        author: "",
        publisher:"Prime",
        pages: "126",
        status: "read",
        rating: "7.2",
        note: "Apresenta influentes teses levantadas por Sigmund Freud com a Psicanálise.",
    },
    {
        image: "./src/book-admiravelmundonovo.jpeg",
        title: "Admirável mundo novo",
        subtitle: "",
        author: "Aldous Huxley",
        publisher: "Biblioteca Azul",
        pages: "312",
        status: "read",
        rating: "9.0",
        note: 'Ao lado de "1984", é uma das obras mais influentes de toda a história. Tal qual a obra de George Orwell, também apresenta um mundo distópico moralmente questionável, com um protagonista deslocado da sociedade e em busca da verdade.',
    },
    {
        image: "./src/book-maisespertoqueodiabo.jpg",
        title: "Mais esperto que o Diabo",
        subtitle: "",
        author: "Napoleon Hil",
        publisher:"Citadel",
        pages: "208",
        status: "read",
        rating: "6.9",
        note: "Essa obra argumenta sobre o impacto da fé e da positividade na vida de um indivíduo. Hill apresenta de forma excêntrica o conceito de medo na mente humana, em contraste com a fé individual.",
    },
    {
        image: "./src/book-veronikadecidemorrer.webp",
        title: "Veronika decide morrer",
        subtitle: "",
        author: "Paulo Coelho",
        publisher:"Gold",
        pages: "240",
        status: "read",
        rating: "8.0",
        note: "",
    },
    {
        image: "./src/book-arevolucaodosbichos.jpg",
        title: "A revolução dos bichos",
        subtitle: "",
        author: "George Orwell",
        publisher:"Leya",
        pages: "319",
        status: "read",
        rating: "8.4",
        note: "",
    },
    {
        image: "./src/book-jogadorn1.jpg",
        title: "Jogador número 1",
        subtitle: "",
        author: "Ernest Clins",
        publisher:"Leya",
        pages: "462",
        status: "read",
        rating: "8.0",
        note: "",
    },
    {
        image: "./src/book-guiadomochileirodasgalaxias.jpeg",
        title: "O Guia do mochileiro das galáxias",
        subtitle: "- Todos os volumes.",
        author: "Douglas Adams",
        publisher:"Arqueiro",
        pages: "672",
        status: "read",
        rating: "9.2",
        note: "Uma das melhores obras - se não a melhor - de Ficção ja escritas. Douglas Adams aborda sua trama de forma irônica e divertida, com personagens carismáticos e uma história memorável.",
    },
]